// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TradingAssistant.Api.Data;

#nullable disable

namespace TradingAssistant.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260213181900_AddAlertRuleAiEnrichEnabled")]
    partial class AddAlertRuleAiEnrichEnabled
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // This migration only adds AiEnrichEnabled to AlertRule.
            // Full model defined in AppDbContextModelSnapshot.
#pragma warning restore 612, 618
        }
    }
}
