using Microsoft.EntityFrameworkCore;
using Serilog;
using TradingAssistant.Api.Data;
using TradingAssistant.Api.Hubs;
using TradingAssistant.Api.Services.Alerts;
using TradingAssistant.Api.Services.AI;
using TradingAssistant.Api.Services.CTrader;
using TradingAssistant.Api.Services.Journal;
using TradingAssistant.Api.Services.Notifications;
using TradingAssistant.Api.Services.Orders;
using Prometheus;

var builder = WebApplication.CreateBuilder(args);

// Configure Serilog
Log.Logger = new LoggerConfiguration()
    .ReadFrom.Configuration(builder.Configuration)
    .Enrich.FromLogContext()
    .WriteTo.Console()
    .CreateLogger();

builder.Host.UseSerilog();

// Database - PostgreSQL for all environments
var connectionString = builder.Configuration.GetConnectionString("DefaultConnection") ?? "";
builder.Services.AddDbContext<AppDbContext>(options =>
    options.UseNpgsql(connectionString));

// Cache - Redis for all environments
var redisConnectionString = builder.Configuration.GetConnectionString("Redis") ?? "localhost:6379";
builder.Services.AddStackExchangeRedisCache(options =>
{
    options.Configuration = redisConnectionString;
    options.InstanceName = "TradingAssistant:";
});

// Health checks
builder.Services.AddHealthChecks()
    .AddNpgSql(connectionString)
    .AddRedis(redisConnectionString);

// SignalR
builder.Services.AddSignalR();

// Controllers & Swagger
builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

// CORS
builder.Services.AddCors(options =>
{
    options.AddPolicy("TradingUI", policy =>
    {
        policy
            .WithOrigins(builder.Configuration["Cors:AllowedOrigins"]?.Split(',') ?? ["http://localhost:4200"])
            .AllowAnyMethod()
            .AllowAnyHeader()
            .AllowCredentials();
    });
});

// cTrader Services
builder.Services.AddHttpClient();
builder.Services.AddSingleton<ICTraderAuthService, CTraderAuthService>();
builder.Services.AddSingleton<ICTraderConnectionManager, CTraderConnectionManager>();
builder.Services.AddSingleton<ICTraderSymbolResolver, CTraderSymbolResolver>();
builder.Services.AddHostedService<CTraderApiAdapter>();
builder.Services.AddSingleton<ICTraderPriceStream, CTraderPriceStream>();
builder.Services.AddSingleton<ICTraderAccountStream, CTraderAccountStream>();
builder.Services.AddScoped<ICTraderOrderExecutor, CTraderOrderExecutor>();

// Alert Services
builder.Services.AddSingleton<AlertEngine>();
builder.Services.AddHostedService<AlertEngine>(sp => sp.GetRequiredService<AlertEngine>());
builder.Services.AddScoped<IAlertRuleRepository, AlertRuleRepository>();

// Journal Services
builder.Services.AddScoped<ITradeJournalService, TradeJournalService>();
builder.Services.AddScoped<ITradeEnricher, TradeEnricher>();
builder.Services.AddScoped<IAnalyticsAggregator, AnalyticsAggregator>();

// Order Services
builder.Services.AddScoped<IOrderManager, OrderManager>();
builder.Services.AddScoped<IPositionSizer, PositionSizer>();
builder.Services.AddScoped<IRiskGuard, RiskGuard>();

// AI Services
builder.Services.AddHttpClient<IAiAnalysisService, OpenCodeZenService>();

// Notification Services
builder.Services.AddSingleton<INotificationService, NotificationService>();
builder.Services.AddHostedService<TelegramBotService>();
builder.Services.AddHttpClient<IWhatsAppService, WhatsAppService>();

var app = builder.Build();

// Configure pipeline
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseSerilogRequestLogging();
app.UseHttpMetrics();
app.UseCors("TradingUI");

app.MapControllers();
app.MapHub<TradingHub>("/hub");
app.MapHealthChecks("/health");
app.MapMetrics();

// Auto-create/update database in development
if (app.Environment.IsDevelopment())
{
    using var scope = app.Services.CreateScope();
    var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
    db.Database.EnsureCreated();

    // EnsureCreated() doesn't alter an existing database, so apply schema patches
    // for tables/columns added after the initial schema was created.
    await db.Database.ExecuteSqlRawAsync("""
        CREATE TABLE IF NOT EXISTS trading.ctrader_tokens (
            "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "AccessToken" text NOT NULL DEFAULT '',
            "RefreshToken" text NOT NULL DEFAULT '',
            "ExpiresAt" timestamp with time zone NOT NULL DEFAULT NOW(),
            "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
            "UpdatedAt" timestamp with time zone
        );
        """);

    await db.Database.ExecuteSqlRawAsync("""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_schema = 'trading' AND table_name = 'symbols'
                AND column_name = 'CTraderSymbolId'
            ) THEN
                ALTER TABLE trading.symbols ADD COLUMN "CTraderSymbolId" bigint NOT NULL DEFAULT 0;
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_symbols_CTraderSymbolId"
                    ON trading.symbols ("CTraderSymbolId") WHERE "CTraderSymbolId" > 0;
            END IF;
        END $$;
        """);
}

Log.Information("Trading Assistant API started");
await app.RunAsync();
